import Link from 'next/link';
import { ArrowRight, BookOpen, Map, Sparkles } from 'lucide-react';
import DestinationCard from '@/components/DestinationCard';
import JsonLd from '@/components/JsonLd';
import { getDestinations } from '@/lib/api';
import { articles } from '@/content/articles';
import { SITE_URL } from '@/lib/site';

export default async function HomePage() {
  const destinations = await getDestinations();
  const featured = [...destinations].sort((a, b) => Number(b.rating) - Number(a.rating)).slice(0, 6);
  const website = { '@context': 'https://schema.org', '@type': 'WebSite', name: 'JawaBali Trip', url: SITE_URL, inLanguage: 'id-ID' };
  return <><JsonLd data={website} />
    <section className="mx-auto max-w-6xl px-4 pt-6 sm:px-6 sm:pt-10"><div className="relative overflow-hidden rounded-3xl bg-slate-950 px-6 py-16 text-white shadow-2xl sm:px-12 sm:py-24"><img src="https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=80" alt="Terasering hijau di Bali" width="1600" height="900" fetchPriority="high" className="absolute inset-0 h-full w-full object-cover opacity-50" /><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/80 to-fuchsia-950/40" /><div className="relative max-w-3xl"><p className="mb-4 text-sm font-black uppercase tracking-[0.18em] text-fuchsia-300">Panduan lokal · Jawa & Bali</p><h1 className="text-4xl font-black leading-tight tracking-tight sm:text-6xl">Rencanakan perjalanan yang lebih jelas, bukan lebih rumit.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">Temukan destinasi, susun anggaran, pahami transportasi, dan gunakan AI sebagai asisten—semuanya dalam satu panduan perjalanan independen.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/destinasi" className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-6 py-4 font-black text-white">Jelajahi destinasi <ArrowRight size={18} /></Link><Link href="/panduan" className="inline-flex items-center justify-center rounded-xl border border-white/40 px-6 py-4 font-black hover:bg-white/10">Baca panduan</Link></div></div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><div className="grid gap-4 md:grid-cols-3">{[[Map,'Destinasi terkurasi','Cari tempat berdasarkan pulau, kota, dan tipe perjalanan.'],[BookOpen,'Panduan praktis','Pelajari itinerary, budget, dan transportasi sebelum berangkat.'],[Sparkles,'Asisten perjalanan AI','Diskusikan kebutuhan perjalanan dan dapatkan ide yang relevan.']].map(([Icon,title,text])=><div key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><Icon className="text-primary" /><h2 className="mt-5 text-xl font-black">{title}</h2><p className="mt-2 leading-7 text-slate-600">{text}</p></div>)}</div></section>
    <section className="mx-auto max-w-6xl px-4 pb-16 sm:px-6"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="font-black uppercase tracking-wider text-primary">Pilihan pembaca</p><h2 className="mt-2 text-3xl font-black tracking-tight">Destinasi populer</h2></div><Link href="/destinasi" className="hidden font-black text-primary sm:block">Lihat semua →</Link></div>{featured.length ? <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{featured.map((destination)=><DestinationCard key={destination.id} destination={destination} />)}</div> : <p className="rounded-2xl bg-white p-8 text-slate-600">Data destinasi sedang tidak tersedia. Silakan kembali beberapa saat lagi.</p>}</section>
    <section className="bg-white"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><p className="font-black uppercase tracking-wider text-primary">Rencanakan dengan percaya diri</p><h2 className="mt-2 text-3xl font-black">Panduan perjalanan terbaru</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{articles.map((article)=><article key={article.slug} className="rounded-2xl border border-slate-200 p-6"><span className="text-xs font-black uppercase tracking-wider text-primary">{article.cluster}</span><h3 className="mt-3 text-xl font-black"><Link href={`/panduan/${article.slug}`} className="hover:text-primary">{article.title}</Link></h3><p className="mt-3 text-sm leading-6 text-slate-600">{article.description}</p><Link href={`/panduan/${article.slug}`} className="mt-5 inline-block text-sm font-black text-primary">Baca artikel →</Link></article>)}</div></div></section>
  </>;
}
