'use client';

import { useState } from 'react';
const API_URL=(process.env.NEXT_PUBLIC_API_URL||'http://localhost:5000/api').replace(/\/+$/,'');

export default function TripAssistant(){
 const [messages,setMessages]=useState([{role:'assistant',content:'Halo! Ceritakan durasi, titik berangkat, budget, jumlah traveler, dan minat perjalananmu di Jawa atau Bali.'}]); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false);
 async function submit(event){event.preventDefault();const message=input.trim();if(!message||loading)return;const next=[...messages,{role:'user',content:message}];setMessages(next);setInput('');setLoading(true);try{const response=await fetch(`${API_URL}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,language:'id',history:next.slice(-8)})});const data=await response.json();if(!response.ok)throw new Error(data.message);setMessages([...next,{role:'assistant',content:data.reply}]);}catch{setMessages([...next,{role:'assistant',content:'Maaf, asisten sedang tidak dapat dihubungi. Coba lagi beberapa saat atau jelajahi halaman destinasi.'}]);}finally{setLoading(false)}}
 return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><div className="max-h-[520px] min-h-[360px] space-y-4 overflow-y-auto p-5 sm:p-7" aria-live="polite">{messages.map((item,index)=><div key={index} className={`flex ${item.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[88%] whitespace-pre-wrap rounded-2xl px-4 py-3 text-sm leading-6 ${item.role==='user'?'bg-primary text-white':'bg-slate-100 text-slate-800'}`}>{item.content}</div></div>)}{loading&&<p className="text-sm text-slate-500">TripAssistant sedang menyusun jawaban…</p>}</div><form onSubmit={submit} className="border-t border-slate-200 p-4"><label htmlFor="chat-message" className="sr-only">Pesan untuk TripAssistant</label><div className="flex flex-col gap-3 sm:flex-row"><textarea id="chat-message" value={input} onChange={(e)=>setInput(e.target.value)} maxLength={1000} rows="2" placeholder="Contoh: Liburan keluarga 3 hari di Bali, budget 5 juta…" className="min-h-14 flex-1 resize-none rounded-xl border border-slate-300 px-4 py-3"/><button disabled={loading} className="rounded-xl bg-primary px-6 py-3 font-black text-white disabled:opacity-60">Kirim</button></div></form></div>
}
