-- Generated from latest destinations CSV. Run sync_latest_destinations.sql for full data sync.
BEGIN;

ALTER TABLE destinations ADD COLUMN IF NOT EXISTS name_id TEXT;

UPDATE destinations SET name_id = 'Monumen Nasional (Monas)' WHERE id = 1;
UPDATE destinations SET name_id = 'Taman Mini Indonesia Indah' WHERE id = 2;
UPDATE destinations SET name_id = 'Kota Tua Jakarta' WHERE id = 3;
UPDATE destinations SET name_id = 'Museum Bank Indonesia' WHERE id = 4;
UPDATE destinations SET name_id = 'Perkampungan Budaya Betawi Setu Babakan' WHERE id = 5;
UPDATE destinations SET name_id = 'Taman Impian Jaya Ancol' WHERE id = 6;
UPDATE destinations SET name_id = 'Kebun Binatang Ragunan' WHERE id = 7;
UPDATE destinations SET name_id = 'Masjid Istiqlal' WHERE id = 8;
UPDATE destinations SET name_id = 'Katedral Jakarta' WHERE id = 9;
UPDATE destinations SET name_id = 'Kepulauan Seribu' WHERE id = 10;
UPDATE destinations SET name_id = 'Pulau Pramuka' WHERE id = 11;
UPDATE destinations SET name_id = 'Pulau Tidung' WHERE id = 12;
UPDATE destinations SET name_id = 'Taman Nasional Ujung Kulon' WHERE id = 13;
UPDATE destinations SET name_id = 'Pantai Tanjung Lesung' WHERE id = 14;
UPDATE destinations SET name_id = 'Pantai Anyer' WHERE id = 15;
UPDATE destinations SET name_id = 'Pantai Carita' WHERE id = 16;
UPDATE destinations SET name_id = 'Pantai Sawarna' WHERE id = 17;
UPDATE destinations SET name_id = 'Kampung Baduy' WHERE id = 18;
UPDATE destinations SET name_id = 'Kawasan Pusaka Banten Lama' WHERE id = 19;
UPDATE destinations SET name_id = 'Pulau Umang' WHERE id = 20;
UPDATE destinations SET name_id = 'Pulau Sangiang' WHERE id = 21;
UPDATE destinations SET name_id = 'Masjid Agung Banten' WHERE id = 22;
UPDATE destinations SET name_id = 'Kawah Putih Ciwidey' WHERE id = 23;
UPDATE destinations SET name_id = 'Tangkuban Perahu' WHERE id = 24;
UPDATE destinations SET name_id = 'Pantai Pangandaran' WHERE id = 25;
UPDATE destinations SET name_id = 'Green Canyon Cukang Taneuh' WHERE id = 26;
UPDATE destinations SET name_id = 'Ranca Upas' WHERE id = 27;
UPDATE destinations SET name_id = 'Situ Patenggang' WHERE id = 28;
UPDATE destinations SET name_id = 'Glamping Lakeside Rancabali' WHERE id = 29;
UPDATE destinations SET name_id = 'Tebing Keraton' WHERE id = 30;
UPDATE destinations SET name_id = 'Stone Garden Citatah' WHERE id = 31;
UPDATE destinations SET name_id = 'Curug Cimahi' WHERE id = 32;
UPDATE destinations SET name_id = 'Saung Angklung Udjo' WHERE id = 33;
UPDATE destinations SET name_id = 'Gedung Sate' WHERE id = 34;
UPDATE destinations SET name_id = 'Jalan Braga' WHERE id = 35;
UPDATE destinations SET name_id = 'Trans Studio Bandung' WHERE id = 36;
UPDATE destinations SET name_id = 'Kampung Naga' WHERE id = 37;
UPDATE destinations SET name_id = 'Gunung Papandayan' WHERE id = 38;
UPDATE destinations SET name_id = 'Pantai Ujung Genteng' WHERE id = 39;
UPDATE destinations SET name_id = 'Bendungan Jatiluhur' WHERE id = 40;
UPDATE destinations SET name_id = 'Pantai Batu Karas' WHERE id = 41;
UPDATE destinations SET name_id = 'Curug Cikaso' WHERE id = 42;
UPDATE destinations SET name_id = 'Taman Safari Indonesia Bogor' WHERE id = 43;
UPDATE destinations SET name_id = 'Kebun Raya Bogor' WHERE id = 44;
UPDATE destinations SET name_id = 'Taman Nasional Gunung Gede Pangrango' WHERE id = 45;
UPDATE destinations SET name_id = 'Geopark Ciletuh' WHERE id = 46;
UPDATE destinations SET name_id = 'Curug Malela' WHERE id = 47;
UPDATE destinations SET name_id = 'Candi Borobudur' WHERE id = 48;
UPDATE destinations SET name_id = 'Taman Nasional Karimunjawa' WHERE id = 49;
UPDATE destinations SET name_id = 'Dataran Tinggi Dieng' WHERE id = 50;
UPDATE destinations SET name_id = 'Kompleks Candi Arjuna' WHERE id = 51;
UPDATE destinations SET name_id = 'Lawu Park' WHERE id = 52;
UPDATE destinations SET name_id = 'Gua Lawa Purbalingga' WHERE id = 53;
UPDATE destinations SET name_id = 'Kebun Teh Kertosari' WHERE id = 54;
UPDATE destinations SET name_id = 'Gardu Pandang Tieng' WHERE id = 55;
UPDATE destinations SET name_id = 'Candi Gedong Songo' WHERE id = 56;
UPDATE destinations SET name_id = 'Kota Lama Semarang' WHERE id = 57;
UPDATE destinations SET name_id = 'Lawang Sewu' WHERE id = 58;
UPDATE destinations SET name_id = 'Masjid Agung Jawa Tengah' WHERE id = 59;
UPDATE destinations SET name_id = 'Museum Kereta Api Ambarawa' WHERE id = 60;
UPDATE destinations SET name_id = 'Umbul Ponggok' WHERE id = 61;
UPDATE destinations SET name_id = 'Air Terjun Grojogan Sewu' WHERE id = 62;
UPDATE destinations SET name_id = 'Tawangmangu' WHERE id = 63;
UPDATE destinations SET name_id = 'Situs Manusia Purba Sangiran' WHERE id = 64;
UPDATE destinations SET name_id = 'Danau Rawa Pening' WHERE id = 65;
UPDATE destinations SET name_id = 'Pantai Menganti' WHERE id = 66;
UPDATE destinations SET name_id = 'Baturraden' WHERE id = 67;
UPDATE destinations SET name_id = 'Curug Lawe' WHERE id = 68;
UPDATE destinations SET name_id = 'Telaga Warna Dieng' WHERE id = 69;
UPDATE destinations SET name_id = 'Kawah Sikidang' WHERE id = 70;
UPDATE destinations SET name_id = 'Bukit Sikunir' WHERE id = 71;
UPDATE destinations SET name_id = 'Candi Mendut' WHERE id = 72;
UPDATE destinations SET name_id = 'Candi Prambanan' WHERE id = 73;
UPDATE destinations SET name_id = 'Jalan Malioboro' WHERE id = 74;
UPDATE destinations SET name_id = 'Tugu Jogja' WHERE id = 75;
UPDATE destinations SET name_id = 'Istana Air Taman Sari' WHERE id = 76;
UPDATE destinations SET name_id = 'HeHa Sky View' WHERE id = 77;
UPDATE destinations SET name_id = 'Pantai Drini' WHERE id = 78;
UPDATE destinations SET name_id = 'Obelix Hills' WHERE id = 79;
UPDATE destinations SET name_id = 'Pantai Parangtritis' WHERE id = 80;
UPDATE destinations SET name_id = 'HeHa Ocean View' WHERE id = 81;
UPDATE destinations SET name_id = 'Tebing Breksi' WHERE id = 82;
UPDATE destinations SET name_id = 'Pantai Slili' WHERE id = 83;
UPDATE destinations SET name_id = 'Pantai Ngobaran' WHERE id = 84;
UPDATE destinations SET name_id = 'Kebun Binatang Gembira Loka' WHERE id = 85;
UPDATE destinations SET name_id = 'Taman Pintar Yogyakarta' WHERE id = 86;
UPDATE destinations SET name_id = 'Pasar Beringharjo' WHERE id = 87;
UPDATE destinations SET name_id = 'Pantai Indrayanti' WHERE id = 88;
UPDATE destinations SET name_id = 'Kaliurang' WHERE id = 89;
UPDATE destinations SET name_id = 'Istana Ratu Boko' WHERE id = 90;
UPDATE destinations SET name_id = 'Goa Pindul' WHERE id = 91;
UPDATE destinations SET name_id = 'Pantai Kukup' WHERE id = 92;
UPDATE destinations SET name_id = 'Candi Plaosan' WHERE id = 93;
UPDATE destinations SET name_id = 'Agrowisata Bhumi Merapi' WHERE id = 94;
UPDATE destinations SET name_id = 'Pantai Gesing' WHERE id = 95;
UPDATE destinations SET name_id = 'Museum Ullen Sentalu' WHERE id = 96;
UPDATE destinations SET name_id = 'Pinus Pengger' WHERE id = 97;
UPDATE destinations SET name_id = 'Kebun Buah Mangunan' WHERE id = 98;
UPDATE destinations SET name_id = 'Gunung Api Purba Nglanggeran' WHERE id = 99;
UPDATE destinations SET name_id = 'Gunung Bromo' WHERE id = 100;
UPDATE destinations SET name_id = 'Kawah Ijen' WHERE id = 101;
UPDATE destinations SET name_id = 'Geopark Ijen' WHERE id = 102;
UPDATE destinations SET name_id = 'Taman Nasional Baluran' WHERE id = 103;
UPDATE destinations SET name_id = 'Air Terjun Tumpak Sewu' WHERE id = 104;
UPDATE destinations SET name_id = 'Gunung Semeru' WHERE id = 105;
UPDATE destinations SET name_id = 'Air Terjun Madakaripura' WHERE id = 106;
UPDATE destinations SET name_id = 'Jatim Park 1' WHERE id = 107;
UPDATE destinations SET name_id = 'Jatim Park 2 Batu Secret Zoo' WHERE id = 108;
UPDATE destinations SET name_id = 'Museum Angkut' WHERE id = 109;
UPDATE destinations SET name_id = 'Batu Night Spectacular' WHERE id = 110;
UPDATE destinations SET name_id = 'Taman Rekreasi Selecta' WHERE id = 111;
UPDATE destinations SET name_id = 'Air Terjun Coban Rondo' WHERE id = 112;
UPDATE destinations SET name_id = 'Kampung Warna-Warni Jodipan' WHERE id = 113;
UPDATE destinations SET name_id = 'Monumen Kapal Selam Surabaya' WHERE id = 114;
UPDATE destinations SET name_id = 'Museum House of Sampoerna' WHERE id = 115;
UPDATE destinations SET name_id = 'Tugu Pahlawan Surabaya' WHERE id = 116;
UPDATE destinations SET name_id = 'Pantai Kenjeran' WHERE id = 117;
UPDATE destinations SET name_id = 'Ranu Kumbolo' WHERE id = 118;
UPDATE destinations SET name_id = 'Pantai Papuma' WHERE id = 119;
UPDATE destinations SET name_id = 'Pantai G-Land Plengkung' WHERE id = 120;
UPDATE destinations SET name_id = 'Taman Nasional Alas Purwo' WHERE id = 121;
UPDATE destinations SET name_id = 'Taman Nasional Meru Betiri' WHERE id = 122;
UPDATE destinations SET name_id = 'Pantai Pulau Merah' WHERE id = 123;
UPDATE destinations SET name_id = 'Pantai Sukamade' WHERE id = 124;
UPDATE destinations SET name_id = 'Desa Ngadas' WHERE id = 125;
UPDATE destinations SET name_id = 'Gunung Kelud' WHERE id = 126;
UPDATE destinations SET name_id = 'Pantai Kuta' WHERE id = 127;
UPDATE destinations SET name_id = 'Pantai Nusa Dua' WHERE id = 128;
UPDATE destinations SET name_id = 'Pantai Jimbaran' WHERE id = 129;
UPDATE destinations SET name_id = 'Pantai Pandawa' WHERE id = 130;
UPDATE destinations SET name_id = 'Pantai Green Bowl' WHERE id = 131;
UPDATE destinations SET name_id = 'Water Blow Nusa Dua' WHERE id = 132;
UPDATE destinations SET name_id = 'Hutan Monyet Sangeh' WHERE id = 133;
UPDATE destinations SET name_id = 'Pura Uluwatu' WHERE id = 134;
UPDATE destinations SET name_id = 'Pura Tanah Lot' WHERE id = 135;
UPDATE destinations SET name_id = 'Pura Ulun Danu Beratan' WHERE id = 136;
UPDATE destinations SET name_id = 'Terasering Sawah Jatiluwih' WHERE id = 137;
UPDATE destinations SET name_id = 'Gunung Batur' WHERE id = 138;
UPDATE destinations SET name_id = 'Danau Batur' WHERE id = 139;
UPDATE destinations SET name_id = 'Pura Kehen' WHERE id = 140;
UPDATE destinations SET name_id = 'Pura Batur' WHERE id = 141;
UPDATE destinations SET name_id = 'Air Terjun Tukad Cepung' WHERE id = 142;
UPDATE destinations SET name_id = 'Desa Trunyan' WHERE id = 143;
UPDATE destinations SET name_id = 'Air Terjun Gitgit' WHERE id = 144;
UPDATE destinations SET name_id = 'Air Saneh' WHERE id = 145;
UPDATE destinations SET name_id = 'Pantai Lovina' WHERE id = 146;
UPDATE destinations SET name_id = 'Pelabuhan Buleleng' WHERE id = 147;
UPDATE destinations SET name_id = 'Taman Air Tirta Gangga' WHERE id = 148;
UPDATE destinations SET name_id = 'Pura Goa Gajah' WHERE id = 149;
UPDATE destinations SET name_id = 'Pura Taman Ayun' WHERE id = 150;
UPDATE destinations SET name_id = 'Desa Penglipuran' WHERE id = 151;
UPDATE destinations SET name_id = 'Pura Besakih' WHERE id = 152;
UPDATE destinations SET name_id = 'Pura Tirta Empul' WHERE id = 153;
UPDATE destinations SET name_id = 'Hutan Monyet Ubud' WHERE id = 154;
UPDATE destinations SET name_id = 'Nusa Penida' WHERE id = 155;
UPDATE destinations SET name_id = 'Pantai Diamond Nusa Penida' WHERE id = 156;
UPDATE destinations SET name_id = 'Pantai Sanur' WHERE id = 157;
UPDATE destinations SET name_id = 'Pantai Seminyak' WHERE id = 158;
UPDATE destinations SET name_id = 'Pantai Canggu' WHERE id = 159;
UPDATE destinations SET name_id = 'Taman Budaya Garuda Wisnu Kencana' WHERE id = 160;
UPDATE destinations SET name_id = 'Bali Safari dan Marine Park' WHERE id = 161;

UPDATE destinations SET name_id = name WHERE name_id IS NULL;

COMMIT;
