-- Run this once in Supabase SQL Editor to add Indonesian destination names.
BEGIN;

ALTER TABLE destinations ADD COLUMN IF NOT EXISTS name_id TEXT;

UPDATE destinations SET name_id = 'Taman Nasional Ujung Kulon' WHERE id = 1;
UPDATE destinations SET name_id = 'Pantai Tanjung Lesung' WHERE id = 2;
UPDATE destinations SET name_id = 'Pantai Anyer' WHERE id = 3;
UPDATE destinations SET name_id = 'Pantai Sawarna' WHERE id = 4;
UPDATE destinations SET name_id = 'Desa Baduy' WHERE id = 5;
UPDATE destinations SET name_id = 'Pantai Carita' WHERE id = 6;
UPDATE destinations SET name_id = 'Pulau Sangiang' WHERE id = 7;
UPDATE destinations SET name_id = 'Curug Putri Tahura Banten' WHERE id = 8;
UPDATE destinations SET name_id = 'Masjid Agung Banten Lama' WHERE id = 9;
UPDATE destinations SET name_id = 'Benteng Speelwijk' WHERE id = 10;
UPDATE destinations SET name_id = 'Monumen Nasional' WHERE id = 11;
UPDATE destinations SET name_id = 'Kota Tua Jakarta' WHERE id = 12;
UPDATE destinations SET name_id = 'Taman Impian Jaya Ancol' WHERE id = 13;
UPDATE destinations SET name_id = 'Taman Nasional Kepulauan Seribu' WHERE id = 14;
UPDATE destinations SET name_id = 'Taman Mini Indonesia Indah' WHERE id = 15;
UPDATE destinations SET name_id = 'Kebun Binatang Ragunan' WHERE id = 16;
UPDATE destinations SET name_id = 'Masjid Istiqlal' WHERE id = 17;
UPDATE destinations SET name_id = 'Katedral Jakarta' WHERE id = 18;
UPDATE destinations SET name_id = 'Perkampungan Budaya Betawi Setu Babakan' WHERE id = 19;
UPDATE destinations SET name_id = 'Museum Nasional Indonesia' WHERE id = 20;
UPDATE destinations SET name_id = 'Kawah Putih' WHERE id = 21;
UPDATE destinations SET name_id = 'Tangkuban Perahu' WHERE id = 22;
UPDATE destinations SET name_id = 'Stone Garden Citatah' WHERE id = 23;
UPDATE destinations SET name_id = 'Green Canyon Pangandaran' WHERE id = 24;
UPDATE destinations SET name_id = 'Pantai Pangandaran' WHERE id = 25;
UPDATE destinations SET name_id = 'Situ Patenggang' WHERE id = 26;
UPDATE destinations SET name_id = 'Curug Cimahi / Air Terjun Pelangi' WHERE id = 27;
UPDATE destinations SET name_id = 'Gunung Papandayan' WHERE id = 28;
UPDATE destinations SET name_id = 'Kampung Naga' WHERE id = 29;
UPDATE destinations SET name_id = 'Kebun Raya Bogor' WHERE id = 30;
UPDATE destinations SET name_id = 'Puncak Pass' WHERE id = 31;
UPDATE destinations SET name_id = 'Pantai Santolo' WHERE id = 32;
UPDATE destinations SET name_id = 'Saung Angklung Udjo' WHERE id = 33;
UPDATE destinations SET name_id = 'Tebing Keraton' WHERE id = 34;
UPDATE destinations SET name_id = 'Jembatan Gantung Situ Gunung' WHERE id = 35;
UPDATE destinations SET name_id = 'Candi Borobudur' WHERE id = 36;
UPDATE destinations SET name_id = 'Candi Prambanan' WHERE id = 37;
UPDATE destinations SET name_id = 'Dataran Tinggi Dieng' WHERE id = 38;
UPDATE destinations SET name_id = 'Taman Nasional Karimunjawa' WHERE id = 39;
UPDATE destinations SET name_id = 'Lawang Sewu' WHERE id = 40;
UPDATE destinations SET name_id = 'Kelenteng Sam Poo Kong' WHERE id = 41;
UPDATE destinations SET name_id = 'Kota Lama Semarang' WHERE id = 42;
UPDATE destinations SET name_id = 'Umbul Ponggok' WHERE id = 43;
UPDATE destinations SET name_id = 'Air Terjun Grojogan Sewu' WHERE id = 44;
UPDATE destinations SET name_id = 'Taman Nasional Gunung Merbabu' WHERE id = 45;
UPDATE destinations SET name_id = 'Candi Cetho' WHERE id = 46;
UPDATE destinations SET name_id = 'Candi Sukuh' WHERE id = 47;
UPDATE destinations SET name_id = 'Baturraden' WHERE id = 48;
UPDATE destinations SET name_id = 'Danau Rawa Pening' WHERE id = 49;
UPDATE destinations SET name_id = 'Candi Gedong Songo' WHERE id = 50;
UPDATE destinations SET name_id = 'Jalan Malioboro' WHERE id = 51;
UPDATE destinations SET name_id = 'Taman Sari' WHERE id = 52;
UPDATE destinations SET name_id = 'Keraton Yogyakarta' WHERE id = 53;
UPDATE destinations SET name_id = 'Pantai Parangtritis' WHERE id = 54;
UPDATE destinations SET name_id = 'Keraton Ratu Boko' WHERE id = 55;
UPDATE destinations SET name_id = 'Goa Jomblang' WHERE id = 56;
UPDATE destinations SET name_id = 'Goa Pindul' WHERE id = 57;
UPDATE destinations SET name_id = 'Gunung Merapi Kaliurang' WHERE id = 58;
UPDATE destinations SET name_id = 'Hutan Pinus Mangunan' WHERE id = 59;
UPDATE destinations SET name_id = 'Pantai Timang' WHERE id = 60;
UPDATE destinations SET name_id = 'Gunung Bromo' WHERE id = 61;
UPDATE destinations SET name_id = 'Kawah Ijen' WHERE id = 62;
UPDATE destinations SET name_id = 'Air Terjun Tumpak Sewu' WHERE id = 63;
UPDATE destinations SET name_id = 'Taman Nasional Baluran' WHERE id = 64;
UPDATE destinations SET name_id = 'Air Terjun Madakaripura' WHERE id = 65;
UPDATE destinations SET name_id = 'Air Terjun Coban Rondo' WHERE id = 66;
UPDATE destinations SET name_id = 'Jatim Park 2' WHERE id = 67;
UPDATE destinations SET name_id = 'Museum Angkut' WHERE id = 68;
UPDATE destinations SET name_id = 'Batu Secret Zoo' WHERE id = 69;
UPDATE destinations SET name_id = 'Pulau Sempu' WHERE id = 70;
UPDATE destinations SET name_id = 'Pantai Papuma' WHERE id = 71;
UPDATE destinations SET name_id = 'Telaga Sarangan' WHERE id = 72;
UPDATE destinations SET name_id = 'Taman Nasional Alas Purwo' WHERE id = 73;
UPDATE destinations SET name_id = 'Jembatan Suramadu' WHERE id = 74;
UPDATE destinations SET name_id = 'Kampung Warna Warni Jodipan' WHERE id = 75;
UPDATE destinations SET name_id = 'Pantai Kuta' WHERE id = 76;
UPDATE destinations SET name_id = 'Pantai Seminyak' WHERE id = 77;
UPDATE destinations SET name_id = 'Pantai Sanur' WHERE id = 78;
UPDATE destinations SET name_id = 'Pantai Nusa Dua' WHERE id = 79;
UPDATE destinations SET name_id = 'Pura Uluwatu' WHERE id = 80;
UPDATE destinations SET name_id = 'Tanah Lot' WHERE id = 81;
UPDATE destinations SET name_id = 'Pura Besakih' WHERE id = 82;
UPDATE destinations SET name_id = 'Pura Tirta Empul' WHERE id = 83;
UPDATE destinations SET name_id = 'Terasering Sawah Tegallalang' WHERE id = 84;
UPDATE destinations SET name_id = 'Mandala Suci Wenara Wana Ubud' WHERE id = 85;
UPDATE destinations SET name_id = 'Bukit Campuhan' WHERE id = 86;
UPDATE destinations SET name_id = 'Air Terjun Tegenungan' WHERE id = 87;
UPDATE destinations SET name_id = 'Air Terjun Sekumpul' WHERE id = 88;
UPDATE destinations SET name_id = 'Gunung Batur' WHERE id = 89;
UPDATE destinations SET name_id = 'Pura Ulun Danu Beratan' WHERE id = 90;
UPDATE destinations SET name_id = 'Terasering Sawah Jatiluwih' WHERE id = 91;
UPDATE destinations SET name_id = 'Garuda Wisnu Kencana' WHERE id = 92;
UPDATE destinations SET name_id = 'Pantai Kelingking' WHERE id = 93;
UPDATE destinations SET name_id = 'Angel''s Billabong' WHERE id = 94;
UPDATE destinations SET name_id = 'Pasih Uug' WHERE id = 95;
UPDATE destinations SET name_id = 'Pantai Amed' WHERE id = 96;
UPDATE destinations SET name_id = 'Pantai Lovina' WHERE id = 97;
UPDATE destinations SET name_id = 'Pulau Menjangan' WHERE id = 98;
UPDATE destinations SET name_id = 'Tirta Gangga' WHERE id = 99;
UPDATE destinations SET name_id = 'Lembah Sidemen' WHERE id = 100;

UPDATE destinations SET name_id = name WHERE name_id IS NULL;

COMMIT;
