export const destinations = [
  ['Borobudur','Java','Central Java','Magelang','culture','Budaya','Culture','Candi Buddha megah dengan relief bersejarah.','A grand Buddhist temple with historic relief panels.','Borobudur menawarkan arsitektur kuno, panorama bukit, dan pengalaman budaya yang kuat untuk perjalanan keluarga maupun pecinta sejarah.','Borobudur offers ancient architecture, hill views, and a rich cultural experience for families and history lovers.','https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=900&q=80','Borobudur, Magelang, Central Java',-7.6079,110.2038,'https://maps.google.com/?q=-7.6079,110.2038','Menjelajah relief, sunrise, museum, fotografi.','Relief walks, sunrise, museum, photography.','Pagi hari saat cuaca cerah.','Early morning on clear days.','Datang lebih awal dan siapkan topi serta air minum.','Arrive early and bring a hat and water.',4.8,120],
  ['Prambanan','Java','Special Region of Yogyakarta','Sleman','culture','Budaya','Culture','Kompleks candi Hindu ikonik dekat Yogyakarta.','An iconic Hindu temple complex near Yogyakarta.','Prambanan cocok untuk wisata budaya, pertunjukan seni, dan perjalanan singkat dari pusat Yogyakarta.','Prambanan is ideal for culture trips, performing arts, and a short journey from central Yogyakarta.','https://images.unsplash.com/photo-1621759748310-8c9cf7c1f016?auto=format&fit=crop&w=900&q=80','Prambanan, Sleman, Yogyakarta',-7.7520,110.4915,'https://maps.google.com/?q=-7.7520,110.4915','Tur candi, foto, pertunjukan Ramayana.','Temple tour, photos, Ramayana performance.','Sore hari menjelang matahari terbenam.','Late afternoon near sunset.','Gabungkan dengan itinerary kota Yogyakarta.','Pair it with a Yogyakarta city itinerary.',4.7,98],
  ['Mount Bromo','Java','East Java','Probolinggo','nature','Alam','Nature','Gunung berapi dengan lautan pasir dan sunrise terkenal.','A volcano with a sand sea and famous sunrise.','Bromo adalah pilihan kuat untuk pencinta alam, petualangan ringan, dan pemandangan dramatis di Jawa Timur.','Bromo is a strong choice for nature lovers, light adventure, and dramatic East Java scenery.','https://images.unsplash.com/photo-1589308454676-22a1467e182b?auto=format&fit=crop&w=900&q=80','Bromo Tengger Semeru National Park',-7.9425,112.9530,'https://maps.google.com/?q=-7.9425,112.9530','Sunrise, jeep tour, trekking ringan.','Sunrise, jeep tour, light trekking.','Musim kemarau, sangat pagi.','Dry season, very early morning.','Udara dingin; bawa jaket tebal.','It gets cold; bring a warm jacket.',4.9,150],
  ['Kawah Ijen','Java','East Java','Banyuwangi','nature','Alam','Nature','Danau kawah asam dengan fenomena api biru.','An acidic crater lake known for blue fire.','Kawah Ijen cocok untuk traveler aktif yang ingin trekking malam dan pemandangan vulkanik unik.','Kawah Ijen suits active travelers seeking night trekking and unique volcanic views.','https://images.unsplash.com/photo-1570789210967-2cac24afeb00?auto=format&fit=crop&w=900&q=80','Ijen, Banyuwangi, East Java',-8.0580,114.2420,'https://maps.google.com/?q=-8.0580,114.2420','Trekking, melihat blue fire, fotografi.','Trekking, blue fire viewing, photography.','Musim kemarau dan dini hari.','Dry season and before dawn.','Perlu stamina baik dan masker gas dari operator lokal.','Requires decent stamina and a gas mask from local operators.',4.8,87],
  ['Tangkuban Perahu','Java','West Java','Bandung Barat','nature','Alam','Nature','Kawah gunung berapi yang mudah dijangkau dari Bandung.','A volcanic crater easily reached from Bandung.','Destinasi ini pas untuk keluarga dan perjalanan singkat dengan suasana pegunungan.','This destination fits families and short mountain getaways.','https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=900&q=80','Lembang, West Bandung',-6.7596,107.6098,'https://maps.google.com/?q=-6.7596,107.6098','Melihat kawah, kuliner, belanja oleh-oleh.','Crater viewing, food stops, souvenir shopping.','Pagi sampai siang.','Morning to noon.','Akses mudah, tetapi akhir pekan bisa ramai.','Easy access, but weekends can be crowded.',4.4,64],
  ['Pantai Pangandaran','Java','West Java','Pangandaran','beach','Pantai','Beach','Pantai populer untuk keluarga, berenang, dan kuliner laut.','A popular beach for families, swimming, and seafood.','Pangandaran menawarkan pantai luas, aktivitas air, dan suasana liburan keluarga yang santai.','Pangandaran offers broad beaches, water activities, and a relaxed family holiday mood.','https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80','Pangandaran, West Java',-7.6897,108.6508,'https://maps.google.com/?q=-7.6897,108.6508','Berenang, seafood, sunset, body rafting sekitar.','Swimming, seafood, sunset, nearby body rafting.','Musim kemarau dan sore hari.','Dry season and late afternoon.','Cek kondisi ombak sebelum berenang.','Check wave conditions before swimming.',4.3,73],
  ['Kota Tua Jakarta','Java','DKI Jakarta','Jakarta','city','Kota & Sejarah','City & History','Kawasan bersejarah dengan museum dan bangunan kolonial.','A historic district with museums and colonial buildings.','Kota Tua cocok untuk wisata sejarah, foto, dan eksplorasi singkat di Jakarta.','Kota Tua is great for history, photos, and a short Jakarta exploration.','https://images.unsplash.com/photo-1555899434-94d1368aa7af?auto=format&fit=crop&w=900&q=80','Kota Tua, West Jakarta',-6.1352,106.8133,'https://maps.google.com/?q=-6.1352,106.8133','Museum, sepeda, foto arsitektur, kuliner.','Museums, cycling, architecture photos, food.','Pagi atau sore.','Morning or late afternoon.','Gunakan transportasi publik untuk menghindari macet.','Use public transport to avoid traffic.',4.2,55],
  ['Malioboro','Java','Special Region of Yogyakarta','Yogyakarta','city','Kota & Kuliner','City & Culinary','Jalan ikonik untuk belanja, kuliner, dan suasana kota.','An iconic street for shopping, food, and city atmosphere.','Malioboro adalah pusat suasana Yogyakarta, cocok untuk wisata kuliner dan belanja oleh-oleh.','Malioboro captures Yogyakarta atmosphere, ideal for food walks and souvenir shopping.','https://images.unsplash.com/photo-1566558358491-5bb5fdb3a2e0?auto=format&fit=crop&w=900&q=80','Malioboro Street, Yogyakarta',-7.7926,110.3658,'https://maps.google.com/?q=-7.7926,110.3658','Belanja, kuliner, jalan kaki, foto malam.','Shopping, food, walking, night photos.','Sore hingga malam.','Evening to night.','Siapkan uang tunai kecil dan alas kaki nyaman.','Prepare small cash and comfortable shoes.',4.5,140],
  ['Dieng Plateau','Java','Central Java','Wonosobo','nature','Alam','Nature','Dataran tinggi dengan telaga, candi, dan udara sejuk.','A highland area with lakes, temples, and cool air.','Dieng cocok untuk pencinta alam dan budaya yang ingin suasana pegunungan tenang.','Dieng suits nature and culture lovers seeking calm mountain scenery.','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80','Dieng, Wonosobo, Central Java',-7.2046,109.9124,'https://maps.google.com/?q=-7.2046,109.9124','Sunrise, telaga warna, candi, kuliner lokal.','Sunrise, colorful lake, temples, local food.','Musim kemarau, pagi hari.','Dry season, morning.','Jalan berkelok dan dingin; rencanakan transportasi.','Winding roads and cold air; plan transport.',4.6,91],
  ['Karimunjawa','Java','Central Java','Jepara','beach','Pantai','Beach','Kepulauan tropis untuk snorkeling dan island hopping.','A tropical island chain for snorkeling and island hopping.','Karimunjawa pas untuk liburan pantai beberapa hari dengan ritme santai dan laut jernih.','Karimunjawa fits multi-day beach trips with a relaxed pace and clear water.','https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=80','Karimunjawa, Jepara, Central Java',-5.8786,110.4331,'https://maps.google.com/?q=-5.8786,110.4331','Snorkeling, island hopping, pantai, seafood.','Snorkeling, island hopping, beaches, seafood.','Musim kemarau saat laut tenang.','Dry season when seas are calm.','Cek jadwal kapal dan cuaca sebelum berangkat.','Check ferry schedules and weather before leaving.',4.7,77],
  ['Ubud','Bali','Bali','Gianyar','culture','Budaya','Culture','Pusat seni, sawah, yoga, dan budaya Bali.','A center for Balinese art, rice fields, yoga, and culture.','Ubud ideal untuk wisata budaya, wellness, kuliner, dan suasana Bali yang lebih tenang.','Ubud is ideal for culture, wellness, food, and a calmer side of Bali.','https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80','Ubud, Gianyar, Bali',-8.5069,115.2625,'https://maps.google.com/?q=-8.5069,115.2625','Sawah, galeri seni, yoga, kuliner, pura.','Rice fields, art galleries, yoga, food, temples.','Pagi hari atau sore.','Morning or late afternoon.','Sewa motor atau driver untuk menjangkau area sekitar.','Rent a scooter or driver to explore nearby areas.',4.8,132],
  ['Kuta Beach','Bali','Bali','Badung','beach','Pantai','Beach','Pantai ramai untuk sunset, surfing pemula, dan hiburan.','A lively beach for sunset, beginner surfing, and entertainment.','Kuta cocok untuk traveler yang ingin pantai mudah diakses dan suasana ramai.','Kuta suits travelers wanting an easy-access beach and lively atmosphere.','https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=900&q=80','Kuta, Badung, Bali',-8.7184,115.1686,'https://maps.google.com/?q=-8.7184,115.1686','Surfing pemula, sunset, kuliner, belanja.','Beginner surfing, sunset, food, shopping.','Sore hari.','Late afternoon.','Area ramai; jaga barang pribadi.','Busy area; watch your belongings.',4.3,115],
  ['Tanah Lot','Bali','Bali','Tabanan','culture','Budaya','Culture','Pura laut ikonik dengan panorama sunset.','An iconic sea temple with sunset views.','Tanah Lot sangat cocok untuk wisata budaya ringan dan foto pemandangan laut.','Tanah Lot is excellent for light cultural travel and ocean-view photos.','https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=900&q=80','Beraban, Tabanan, Bali',-8.6212,115.0868,'https://maps.google.com/?q=-8.6212,115.0868','Melihat pura, sunset, foto, pasar seni.','Temple viewing, sunset, photos, art market.','Sore menjelang sunset.','Late afternoon before sunset.','Datang lebih awal untuk tempat foto yang nyaman.','Arrive early for comfortable photo spots.',4.6,101],
  ['Uluwatu','Bali','Bali','Badung','culture','Budaya','Culture','Pura tebing laut dengan tari Kecak dan sunset.','A cliffside sea temple with Kecak dance and sunset.','Uluwatu menawarkan kombinasi budaya, tebing dramatis, dan pantai sekitar yang indah.','Uluwatu combines culture, dramatic cliffs, and beautiful nearby beaches.','https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=900&q=80','Pecatu, Badung, Bali',-8.8291,115.0849,'https://maps.google.com/?q=-8.8291,115.0849','Pura, tari Kecak, sunset, pantai tebing.','Temple, Kecak dance, sunset, cliff beaches.','Sore hari.','Late afternoon.','Pesan tiket Kecak lebih awal saat musim ramai.','Book Kecak tickets early in high season.',4.7,119],
  ['Nusa Penida','Bali','Bali','Klungkung','beach','Pantai','Beach','Pulau dengan tebing, pantai dramatis, dan laut biru.','An island with cliffs, dramatic beaches, and blue sea.','Nusa Penida cocok untuk petualangan pantai dan fotografi, terutama bila punya satu hari penuh atau lebih.','Nusa Penida suits beach adventure and photography, especially with a full day or more.','https://images.unsplash.com/photo-1573790387438-4da905039392?auto=format&fit=crop&w=900&q=80','Nusa Penida, Klungkung, Bali',-8.7278,115.5444,'https://maps.google.com/?q=-8.7278,115.5444','Kelingking, snorkeling, pantai, viewpoint.','Kelingking, snorkeling, beaches, viewpoints.','Musim kemarau, pagi berangkat.','Dry season, early departure.','Jalan cukup menantang; gunakan driver lokal jika perlu.','Roads can be challenging; use a local driver if needed.',4.8,126],
  ['Sanur','Bali','Bali','Denpasar','beach','Pantai','Beach','Pantai tenang dengan sunrise dan jalur pejalan kaki.','A calm beach with sunrise and a seaside path.','Sanur pas untuk keluarga, pasangan, dan traveler yang mencari pantai lebih tenang.','Sanur fits families, couples, and travelers seeking a quieter beach.','https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?auto=format&fit=crop&w=900&q=80','Sanur, Denpasar, Bali',-8.6930,115.2625,'https://maps.google.com/?q=-8.6930,115.2625','Sunrise, sepeda, kano, kuliner tepi pantai.','Sunrise, cycling, canoeing, seaside food.','Pagi hari.','Morning.','Cocok sebagai titik berangkat ke Nusa Penida.','Useful as a departure point to Nusa Penida.',4.5,88],
  ['Bedugul','Bali','Bali','Tabanan','nature','Alam','Nature','Kawasan danau dan pegunungan dengan pura Ulun Danu.','A lake and mountain area with Ulun Danu temple.','Bedugul cocok untuk udara sejuk, kebun raya, dan wisata keluarga di Bali tengah.','Bedugul is great for cool air, botanical gardens, and family trips in central Bali.','https://images.unsplash.com/photo-1604999333679-b86d54738315?auto=format&fit=crop&w=900&q=80','Bedugul, Tabanan, Bali',-8.2754,115.1668,'https://maps.google.com/?q=-8.2754,115.1668','Pura danau, kebun raya, foto, piknik.','Lake temple, botanical garden, photos, picnic.','Pagi hingga siang.','Morning to noon.','Bawa jaket ringan karena udara lebih sejuk.','Bring a light jacket for cooler air.',4.5,76],
  ['Mount Batur','Bali','Bali','Bangli','nature','Alam','Nature','Gunung populer untuk trekking sunrise di Bali.','A popular mountain for sunrise trekking in Bali.','Mount Batur cocok untuk traveler aktif yang ingin pengalaman sunrise dan panorama kaldera.','Mount Batur suits active travelers seeking sunrise and caldera views.','https://images.unsplash.com/photo-1512100356356-de1b84283e18?auto=format&fit=crop&w=900&q=80','Kintamani, Bangli, Bali',-8.2423,115.3754,'https://maps.google.com/?q=-8.2423,115.3754','Trekking sunrise, hot spring, panorama danau.','Sunrise trekking, hot springs, lake panorama.','Dini hari saat cuaca cerah.','Before dawn in clear weather.','Gunakan pemandu dan sepatu yang nyaman.','Use a guide and comfortable shoes.',4.7,93],
  ['Tirta Empul','Bali','Bali','Gianyar','culture','Budaya','Culture','Pura air suci untuk pengalaman budaya Bali.','A holy water temple for Balinese cultural experience.','Tirta Empul cocok untuk memahami tradisi Bali dengan suasana spiritual dan arsitektur pura.','Tirta Empul is good for understanding Balinese tradition through spiritual atmosphere and temple architecture.','https://images.unsplash.com/photo-1604841956658-7f5c372a07bf?auto=format&fit=crop&w=900&q=80','Tampaksiring, Gianyar, Bali',-8.4158,115.3152,'https://maps.google.com/?q=-8.4158,115.3152','Melihat pura, ritual melukat, fotografi budaya.','Temple viewing, purification ritual, cultural photography.','Pagi hari.','Morning.','Hormati aturan pakaian dan area sembahyang.','Respect dress rules and prayer areas.',4.6,69],
  ['Garuda Wisnu Kencana','Bali','Bali','Badung','culture','Budaya','Culture','Taman budaya dengan patung raksasa GWK.','A cultural park with the giant GWK statue.','GWK cocok untuk keluarga, pertunjukan budaya, dan kunjungan mudah di Bali selatan.','GWK suits families, cultural shows, and an easy visit in south Bali.','https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=900&q=80','Ungasan, Badung, Bali',-8.8104,115.1676,'https://maps.google.com/?q=-8.8104,115.1676','Patung GWK, pertunjukan budaya, foto, taman.','GWK statue, cultural shows, photos, park walk.','Sore hari.','Late afternoon.','Cek jadwal pertunjukan untuk kunjungan terbaik.','Check show schedules for the best visit.',4.4,82]
];

const fields = [
  'name', 'island', 'province', 'city', 'category_key', 'category_id', 'category_en',
  'short_description_id', 'short_description_en', 'description_id', 'description_en',
  'image_url', 'address', 'latitude', 'longitude', 'google_maps_url', 'activities_id',
  'activities_en', 'best_time_to_visit_id', 'best_time_to_visit_en', 'travel_notes_id',
  'travel_notes_en', 'seed_rating', 'seed_review_count'
];

const nameIdByName = {
  Borobudur: 'Candi Borobudur',
  Prambanan: 'Candi Prambanan',
  'Mount Bromo': 'Gunung Bromo',
  'Kawah Ijen': 'Kawah Ijen',
  'Tangkuban Perahu': 'Tangkuban Perahu',
  'Pantai Pangandaran': 'Pantai Pangandaran',
  'Kota Tua Jakarta': 'Kota Tua Jakarta',
  Malioboro: 'Jalan Malioboro',
  'Dieng Plateau': 'Dataran Tinggi Dieng',
  Karimunjawa: 'Karimunjawa',
  Ubud: 'Ubud',
  'Kuta Beach': 'Pantai Kuta',
  'Tanah Lot': 'Tanah Lot',
  Uluwatu: 'Pura Uluwatu',
  'Nusa Penida': 'Nusa Penida',
  Sanur: 'Pantai Sanur',
  Bedugul: 'Bedugul',
  'Mount Batur': 'Gunung Batur',
  'Tirta Empul': 'Pura Tirta Empul',
  'Garuda Wisnu Kencana': 'Garuda Wisnu Kencana'
};

const sourceByName = {
  Borobudur: ['UNESCO World Heritage Centre', 'https://whc.unesco.org/en/list/592/'],
  Prambanan: ['UNESCO World Heritage Centre', 'https://whc.unesco.org/en/list/642/'],
  'Mount Bromo': ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/java/bromo-tengger-semeru-national-park'],
  'Kawah Ijen': ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/java/banyuwangi/ijen-crater'],
  'Tangkuban Perahu': ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/java/bandung'],
  'Pantai Pangandaran': ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/java/pangandaran'],
  'Kota Tua Jakarta': ['Jakarta Tourism', 'https://www.jakarta-tourism.go.id/'],
  Malioboro: ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/java/yogyakarta'],
  'Dieng Plateau': ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/java/dieng-plateau'],
  Karimunjawa: ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/java/karimunjawa'],
  Ubud: ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/ubud'],
  'Kuta Beach': ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/kuta'],
  'Tanah Lot': ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/tanah-lot'],
  Uluwatu: ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/uluwatu'],
  'Nusa Penida': ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/nusa-penida'],
  Sanur: ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/sanur'],
  Bedugul: ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/bedugul'],
  'Mount Batur': ['UNESCO Global Geoparks', 'https://www.unesco.org/en/iggp/geoparks/batur'],
  'Tirta Empul': ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/tampaksiring'],
  'Garuda Wisnu Kencana': ['Indonesia Travel', 'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/garuda-wisnu-kencana']
};

export const seedDestinations = destinations.map((row, index) => {
  const item = Object.fromEntries(fields.map((field, fieldIndex) => [field, row[fieldIndex]]));
  const [sourceName, sourceUrl] = sourceByName[item.name] || ['Indonesia Travel', 'https://www.indonesia.travel/'];
  return {
    id: index + 1,
    ...item,
    name_id: nameIdByName[item.name] || item.name,
    source_name: sourceName,
    source_url: sourceUrl
  };
});
